### PR TITLE
Overview page of published OSGi artifacts on Maven Central

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
This is work in progress, but from my perspective such an overview page is missing currently from your documentation and developers have difficulties figuring out which Maven dependencies to reference. WDYT?

**Review by bjhargrave — CHANGES_REQUESTED** [review]
This seems like something that will be constantly out of date. There are many many artifactIds under the org.osgi groupId (https://search.maven.org/search?q=g:org.osgi) and I don't want to attempt to list them all on this documentation website.

It would be fine to have a page which documents the groupId (org.osgi) along with a general description of the various artifactIds. But we should not try to pretend to have an exhaustive and complete list here.

**Comment by kwin** [comment]
The problem is that some packages are contained in multiple artifacts .e.g.`osgi.core` vs `org.osgi.framework`, so at least for those chapters which are covered by more than one artifact a documentation hint is necessary! Also describing how to figure out the artifact id from the chapter name (hopefully there is a naming convention) would be really appreciated.

**Comment by bjhargrave** [comment]
> describing how to figure out the artifact id from the chapter name (hopefully there is a naming convention) would be really appreciated.

Well the primary package name is used as the artifactId. You can also search maven central by package name: https://search.maven.org/search?q=fc:org.osgi.service.component.propertytypes

We also should not suggest using osgi.cmpn as we are recommending using the individual artifacts. Otherwise we can say the osgi.* artifacts are aggregations of the other org.osgi.* artifacts.

**Comment by kwin** [comment]
@bjhargrave WDYT about the updated version in https://github.com/osgi/docs/commit/4facb315f01c39be7d6e1f9ab544412f67b74375?

Also I don't see a link from osgi.org to docs.osgi.org which would be useful for developers. That way docs.osgi.org would get more attention.

**Review by bjhargrave — APPROVED** [review]

**Comment by bjhargrave** [comment]
Please squash and amend your commit so that the commit message includes a `Signed-off-by`. I've enabled the DCO check.

> Also I don't see a link from osgi.org to docs.osgi.org which would be useful for developers. That way docs.osgi.org would get more attention.

https://www.osgi.org/developer/specifications/ for example has many links to docs.osgi.org. But more work could be done...

**Comment by bjhargrave** [comment]
Thanks!

**Pull request merged**
